# Generated by Django 5.1.4 on 2024-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_financialsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='accessed_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
