# Generated by Django 5.1.4 on 2024-12-10 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_financialtransaction_accessed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsummary',
            name='Association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.association'),
            preserve_default=False,
        ),
    ]
