# Generated by Django 5.1.4 on 2024-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_financialsummary_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='building_number_end',
        ),
        migrations.RemoveField(
            model_name='association',
            name='building_number_start',
        ),
        migrations.AddField(
            model_name='association',
            name='building_numbers',
            field=models.CharField(default='91 92 93 94 95 96 97 98', max_length=100),
            preserve_default=False,
        ),
    ]
