# Generated by Django 5.1.4 on 2024-12-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_association_building_number_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='current_member',
            field=models.BooleanField(default=True),
        ),
    ]
