# Generated by Django 5.1.4 on 2024-12-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_householdmember_current_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_accepted_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
