# Generated by Django 5.1.4 on 2024-12-18 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_invoice_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='group',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
