# Generated by Django 5.1.4 on 2024-12-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_invoice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
