# Generated by Django 5.1.4 on 2024-12-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_financialtransaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
