# Generated by Django 5.1.4 on 2024-12-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_remove_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
