# Generated by Django 5.1.4 on 2024-12-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_household_building_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='building_no',
            field=models.CharField(max_length=100),
        ),
    ]
