"""
Django settings for CMS project.

Generated by 'django-admin startproject' using Django 4.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xl2w1)z!f9&=99pc0vjbxv5l6zjkte*o&v%1+8#1by7im*f31)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'API.CustomUser'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd party
    'rest_framework',


    # apps
    "API"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    'site_title': 'My Admin Panel',
    'site_header': 'My Admin Panel Header',
    'site_brand': 'MyApp',
    'welcome_sign': 'Welcome to MyApp Admin!',
    'copyright': 'Copyright © 2024 MyApp',
    'search_model': 'auth.User',
    'user_avatar': None,
    'icons': {
        'auth.user': 'fas fa-user',
        'API.association': 'fas fa-users',
        'API.customuser': 'fas fa-user-cog',
        'API.household': 'fas fa-home',
        'API.householdmember': 'fas fa-users',
        'API.invoice': 'fas fa-file-invoice',
        'API.event': 'fas fa-calendar-alt',
        'API.eventattendance': 'fas fa-check-circle',
        'API.project': 'fas fa-project-diagram',
        'API.projectprogress': 'fas fa-tasks',
        'API.financialtransaction': 'fas fa-exchange-alt',
        'API.financialsummary': 'fas fa-wallet',
    },
    'topmenu_links': [
        {'name': 'Home', 'url': '/', 'icon': 'fas fa-home'},
        {'name': 'Documentation', 'url': 'https://docs.example.com',
            'icon': 'fas fa-book'},
        {'name': 'Support', 'url': 'https://support.example.com',
            'icon': 'fas fa-life-ring'},
    ],
    'usermenu_links': [
        {'name': 'Profile', 'url': 'profile/', 'icon': 'fas fa-user'},
        {'name': 'Logout', 'url': 'logout/', 'icon': 'fas fa-sign-out-alt'},
    ],
    'show_ui_builder': True,
    'hide_apps': [],
    'hide_models': [],
    'order_with_respect_to': ['auth', 'myapp'],
}
